// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using dashmottu.API.Infrastructure.Data.AppData;

#nullable disable

namespace dashmottu.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250924204530_Incial")]
    partial class Incial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dashmottu.API.Domain.Entities.EnderecoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ENDERECO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PATIO");

                    b.HasKey("Id");

                    b.HasIndex("PatioId")
                        .IsUnique();

                    b.ToTable("ENDERECO");
                });

            modelBuilder.Entity("dashmottu.API.Domain.Entities.LoginEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOGIN");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PATIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("PatioId")
                        .IsUnique();

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("LOGIN");
                });

            modelBuilder.Entity("dashmottu.API.Domain.Entities.MotoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodTag")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("COD_TAG");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MODELO");

                    b.Property<int?>("PatioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PATIO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PLACA");

                    b.Property<double?>("PosicaoX")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("POSICAO_X");

                    b.Property<double?>("PosicaoY")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("POSICAO_Y");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("MOTOS");
                });

            modelBuilder.Entity("dashmottu.API.Domain.Entities.PatioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PATIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UrlImgPlanta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("URL_IMAGEM");

                    b.HasKey("Id");

                    b.ToTable("PATIO");
                });

            modelBuilder.Entity("dashmottu.API.Domain.Entities.EnderecoEntity", b =>
                {
                    b.HasOne("dashmottu.API.Domain.Entities.PatioEntity", "Patio")
                        .WithOne("Endereco")
                        .HasForeignKey("dashmottu.API.Domain.Entities.EnderecoEntity", "PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("dashmottu.API.Domain.Entities.LoginEntity", b =>
                {
                    b.HasOne("dashmottu.API.Domain.Entities.PatioEntity", "Patio")
                        .WithOne("Login")
                        .HasForeignKey("dashmottu.API.Domain.Entities.LoginEntity", "PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("dashmottu.API.Domain.Entities.MotoEntity", b =>
                {
                    b.HasOne("dashmottu.API.Domain.Entities.PatioEntity", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("dashmottu.API.Domain.Entities.PatioEntity", b =>
                {
                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
